title: Sean J. Taylor
email: NA
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://seanjtaylor.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: seanjtaylor
github_username:  seanjtaylor

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

# Setup
plugins: [jekyll-redirect-from]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
